apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.lifevaultnative'
version = '1.0.0'

expoModule {
  canBePublished false
}

android {
  namespace 'expo.modules.lifevaultnative'

  defaultConfig {
    minSdkVersion 28
  }

  buildFeatures {
    buildConfig true
  }

  packagingOptions {
    resources {
      excludes += ['META-INF/versions/9/OSGI-INF/MANIFEST.MF']
    }
  }
}

dependencies {
  implementation 'org.bouncycastle:bcprov-jdk18on:1.84'
  implementation 'net.zetetic:sqlcipher-android:4.17.0@aar'
  implementation 'androidx.sqlite:sqlite:2.6.2'
  implementation 'androidx.biometric:biometric:1.1.0'

  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.json:json:20250517'
}
