#!/usr/bin/env python3
"""Harden and validate the Android project generated by Expo prebuild."""
from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HEADING = "GENERATED ANDROID SECURITY VALIDATION FAILED"
ANDROID_NS = "http://schemas.android.com/apk/res/android"
ATTR = lambda name: f"{{{ANDROID_NS}}}{name}"
UPDATES = {
    "android.minSdkVersion": "28",
    "android.compileSdkVersion": "36",
    "android.targetSdkVersion": "36",
    "org.gradle.jvmargs": "-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8",
    "reactNativeArchitectures": "arm64-v8a",
}


def fail(errors: list[str]) -> int:
    print(HEADING)
    for error in errors:
        print(f"- {error}")
    return 1


def update_properties(path: Path, errors: list[str]) -> None:
    if not path.is_file():
        errors.append(f"Expo prebuild did not create {path}")
        return
    try:
        original = path.read_text(encoding="utf-8")
    except OSError as error:
        errors.append(f"Could not read {path}: {error}")
        return

    output: list[str] = []
    written: set[str] = set()
    for line in original.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "!")):
            output.append(line)
            continue
        if "=" not in line and ":" not in line:
            output.append(line)
            continue
        separator = "=" if "=" in line else ":"
        key = line.split(separator, 1)[0].strip()
        if key in UPDATES:
            if key not in written:
                output.append(f"{key}={UPDATES[key]}")
                written.add(key)
        else:
            output.append(line)
    for key, value in UPDATES.items():
        if key not in written:
            output.append(f"{key}={value}")
    try:
        path.write_text("\n".join(output) + "\n", encoding="utf-8")
    except OSError as error:
        errors.append(f"Could not write {path}: {error}")
        return

    parsed: dict[str, str] = {}
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        errors.append(f"Could not re-read {path}: {error}")
        return
    for line_number, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "!")):
            continue
        if "=" not in line and ":" not in line:
            continue
        separator = "=" if "=" in line else ":"
        key, value = line.split(separator, 1)
        key = key.strip()
        value = value.strip()
        if key in parsed:
            errors.append(f"Duplicate Gradle property after normalisation: {key}")
        parsed[key] = value
        if key.startswith("android.") and "org.gradle." in value:
            errors.append(f"Concatenated Gradle properties remain on line {line_number}: {line!r}")

    for key, expected in UPDATES.items():
        if parsed.get(key) != expected:
            errors.append(f"{key}: expected {expected!r}, found {parsed.get(key)!r}")
    for key in ("android.minSdkVersion", "android.compileSdkVersion", "android.targetSdkVersion"):
        value = parsed.get(key, "")
        if value and not re.fullmatch(r"\d+", value):
            errors.append(f"{key} is not a plain integer: {value!r}")


def validate_rules(path: Path, errors: list[str]) -> None:
    if not path.is_file():
        errors.append(f"Secure data-extraction rules were not generated: {path}")
        return
    try:
        root = ET.parse(path).getroot()
    except (ET.ParseError, OSError) as error:
        errors.append(f"Could not parse data-extraction rules: {error}")
        return
    if root.tag != "data-extraction-rules":
        errors.append(f"Invalid data-extraction-rules root element: {root.tag}")
        return
    sections = {child.tag: child for child in root}
    expected_sections = {"cloud-backup", "device-transfer"}
    if set(sections) != expected_sections:
        errors.append(f"Expected sections {sorted(expected_sections)}, found {sorted(sections)}")
        return
    if sections["cloud-backup"].attrib.get("disableIfNoEncryptionCapabilities") != "true":
        errors.append("cloud-backup must disable backup when encryption capabilities are unavailable")
    expected_exclusions = {(domain, ".") for domain in ("root", "file", "database", "sharedpref", "external", "device_root", "device_file", "device_database", "device_sharedpref")}
    for section_name, section in sections.items():
        unexpected_children = [child.tag for child in section if child.tag != "exclude"]
        if unexpected_children:
            errors.append(f"{section_name} contains unexpected elements: {unexpected_children}")
        exclusions = {(entry.attrib.get("domain"), entry.attrib.get("path")) for entry in section if entry.tag == "exclude"}
        if exclusions != expected_exclusions:
            errors.append(f"{section_name} exclusions are incomplete or invalid: {sorted(exclusions)}")


def validate_manifest(path: Path, errors: list[str]) -> None:
    if not path.is_file():
        errors.append(f"Generated Android manifest is missing: {path}")
        return
    try:
        root = ET.parse(path).getroot()
    except (ET.ParseError, OSError) as error:
        errors.append(f"Could not parse generated Android manifest: {error}")
        return
    application = root.find("application")
    if application is None:
        errors.append("Generated Android manifest has no application element")
        return
    expected = {
        "allowBackup": "false",
        "fullBackupContent": "false",
        "dataExtractionRules": "@xml/life_vault_data_extraction_rules",
        "usesCleartextTraffic": "false",
    }
    for name, value in expected.items():
        actual = application.attrib.get(ATTR(name))
        if actual != value:
            errors.append(f"Generated manifest application android:{name}: expected {value!r}, found {actual!r}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", default=".", help="Repository root containing the generated android directory")
    args = parser.parse_args()
    project_root = Path(args.project_root).resolve()
    android = project_root / "android"
    errors: list[str] = []
    try:
        update_properties(android / "gradle.properties", errors)
        validate_rules(android / "app/src/main/res/xml/life_vault_data_extraction_rules.xml", errors)
        validate_manifest(android / "app/src/main/AndroidManifest.xml", errors)
    except Exception as error:
        errors.append(f"Validator could not complete: {type(error).__name__}: {error}")
    if errors:
        return fail(errors)
    print("Generated Android security inputs validated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
